author: Crepez
description: Adds seperate inventories per world and gamemode and stuff!
main: de.cubenation.cninventories.CNInventoriesPlugin
name: CNInventories
version: "${project.version}"
load: postworld
api-version: 1.13
depend:
  - Bedrock
  - WorldEdit
database: false
commands:
    inventory:
      description: CNInventories Base Command. See '/inventory help' for further information
    ${project.artifactId}:
        description: CNInventories Settings Command